package modelo;
// Generated 05-jun-2025 10:06:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String dniCliente;
     private String nombre;
     private String email;
     private String contrasenia;
     private int telefono;
     private Set vehiculos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String dniCliente, String nombre, String email, String contrasenia, int telefono) {
        this.dniCliente = dniCliente;
        this.nombre = nombre;
        this.email = email;
        this.contrasenia = contrasenia;
        this.telefono = telefono;
    }
    public Cliente(String dniCliente, String nombre, String email, String contrasenia, int telefono, Set vehiculos) {
       this.dniCliente = dniCliente;
       this.nombre = nombre;
       this.email = email;
       this.contrasenia = contrasenia;
       this.telefono = telefono;
       this.vehiculos = vehiculos;
    }
   
    public String getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(String dniCliente) {
        this.dniCliente = dniCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


