package modelo;
// Generated 03-jun-2025 9:41:35 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int idFactura;
     private Cita cita;
     private double importeTotal;
     private Date fecha;

    public Factura() {
    }

    public Factura(int idFactura, Cita cita, double importeTotal, Date fecha) {
       this.idFactura = idFactura;
       this.cita = cita;
       this.importeTotal = importeTotal;
       this.fecha = fecha;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public double getImporteTotal() {
        return this.importeTotal;
    }
    
    public void setImporteTotal(double importeTotal) {
        this.importeTotal = importeTotal;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


