package modelo;
// Generated 05-jun-2025 10:06:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Reparacion reparacion;
     private double importeTotal;
     private Date fecha;

    public Factura() {
    }

    public Factura(Reparacion reparacion, double importeTotal, Date fecha) {
       this.reparacion = reparacion;
       this.importeTotal = importeTotal;
       this.fecha = fecha;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Reparacion getReparacion() {
        return this.reparacion;
    }
    
    public void setReparacion(Reparacion reparacion) {
        this.reparacion = reparacion;
    }
    public double getImporteTotal() {
        return this.importeTotal;
    }
    
    public void setImporteTotal(double importeTotal) {
        this.importeTotal = importeTotal;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


