package modelo;
// Generated 03-jun-2025 9:41:35 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private int idHistorial;
     private Vehiculo vehiculo;

    public Historial() {
    }

    public Historial(int idHistorial, Vehiculo vehiculo) {
       this.idHistorial = idHistorial;
       this.vehiculo = vehiculo;
    }
   
    public int getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(int idHistorial) {
        this.idHistorial = idHistorial;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }




}


