package modelo;
// Generated 05-jun-2025 10:06:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mecanico generated by hbm2java
 */
public class Mecanico  implements java.io.Serializable {


     private String dniMecanico;
     private int salario;
     private String nombre;
     private String contrasenia;
     private String rama;
     private Set citas = new HashSet(0);

    public Mecanico() {
    }

	
    public Mecanico(String dniMecanico, int salario, String nombre, String contrasenia, String rama) {
        this.dniMecanico = dniMecanico;
        this.salario = salario;
        this.nombre = nombre;
        this.contrasenia = contrasenia;
        this.rama = rama;
    }
    public Mecanico(String dniMecanico, int salario, String nombre, String contrasenia, String rama, Set citas) {
       this.dniMecanico = dniMecanico;
       this.salario = salario;
       this.nombre = nombre;
       this.contrasenia = contrasenia;
       this.rama = rama;
       this.citas = citas;
    }
   
    public String getDniMecanico() {
        return this.dniMecanico;
    }
    
    public void setDniMecanico(String dniMecanico) {
        this.dniMecanico = dniMecanico;
    }
    public int getSalario() {
        return this.salario;
    }
    
    public void setSalario(int salario) {
        this.salario = salario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getRama() {
        return this.rama;
    }
    
    public void setRama(String rama) {
        this.rama = rama;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


