package modelo;
// Generated 05-jun-2025 10:06:04 by Hibernate Tools 4.3.1



/**
 * Piezas generated by hbm2java
 */
public class Piezas  implements java.io.Serializable {


     private Integer idPieza;
     private Proveedor proveedor;
     private Reparacion reparacion;
     private String nombrePieza;

    public Piezas() {
    }

    public Piezas(Proveedor proveedor, Reparacion reparacion, String nombrePieza) {
       this.proveedor = proveedor;
       this.reparacion = reparacion;
       this.nombrePieza = nombrePieza;
    }
   
    public Integer getIdPieza() {
        return this.idPieza;
    }
    
    public void setIdPieza(Integer idPieza) {
        this.idPieza = idPieza;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Reparacion getReparacion() {
        return this.reparacion;
    }
    
    public void setReparacion(Reparacion reparacion) {
        this.reparacion = reparacion;
    }
    public String getNombrePieza() {
        return this.nombrePieza;
    }
    
    public void setNombrePieza(String nombrePieza) {
        this.nombrePieza = nombrePieza;
    }




}


