package modelo;
// Generated 03-jun-2025 9:41:35 by Hibernate Tools 4.3.1



/**
 * Piezas generated by hbm2java
 */
public class Piezas  implements java.io.Serializable {


     private int idPieza;
     private Reparacion reparacion;
     private String nombrePieza;

    public Piezas() {
    }

    public Piezas(int idPieza, Reparacion reparacion, String nombrePieza) {
       this.idPieza = idPieza;
       this.reparacion = reparacion;
       this.nombrePieza = nombrePieza;
    }
   
    public int getIdPieza() {
        return this.idPieza;
    }
    
    public void setIdPieza(int idPieza) {
        this.idPieza = idPieza;
    }
    public Reparacion getReparacion() {
        return this.reparacion;
    }
    
    public void setReparacion(Reparacion reparacion) {
        this.reparacion = reparacion;
    }
    public String getNombrePieza() {
        return this.nombrePieza;
    }
    
    public void setNombrePieza(String nombrePieza) {
        this.nombrePieza = nombrePieza;
    }




}


