package modelo;
// Generated 05-jun-2025 10:06:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String nombre;
     private String email;
     private String direccion;
     private int telefono;
     private Set piezases = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre, String email, String direccion, int telefono) {
        this.nombre = nombre;
        this.email = email;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Proveedor(String nombre, String email, String direccion, int telefono, Set piezases) {
       this.nombre = nombre;
       this.email = email;
       this.direccion = direccion;
       this.telefono = telefono;
       this.piezases = piezases;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Set getPiezases() {
        return this.piezases;
    }
    
    public void setPiezases(Set piezases) {
        this.piezases = piezases;
    }




}


