package modelo;
// Generated 05-jun-2025 10:06:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reparacion generated by hbm2java
 */
public class Reparacion  implements java.io.Serializable {


     private Integer idReparacion;
     private Cita cita;
     private String tipo;
     private double precio;
     private String comentario;
     private Set facturas = new HashSet(0);
     private Set piezases = new HashSet(0);

    public Reparacion() {
    }

	
    public Reparacion(Cita cita, String tipo, double precio, String comentario) {
        this.cita = cita;
        this.tipo = tipo;
        this.precio = precio;
        this.comentario = comentario;
    }
    public Reparacion(Cita cita, String tipo, double precio, String comentario, Set facturas, Set piezases) {
       this.cita = cita;
       this.tipo = tipo;
       this.precio = precio;
       this.comentario = comentario;
       this.facturas = facturas;
       this.piezases = piezases;
    }
   
    public Integer getIdReparacion() {
        return this.idReparacion;
    }
    
    public void setIdReparacion(Integer idReparacion) {
        this.idReparacion = idReparacion;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getPiezases() {
        return this.piezases;
    }
    
    public void setPiezases(Set piezases) {
        this.piezases = piezases;
    }




}


