package modelo;
// Generated 05-jun-2025 10:06:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String matricula;
     private Cliente cliente;
     private String marca;
     private Set citas = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String matricula, Cliente cliente) {
        this.matricula = matricula;
        this.cliente = cliente;
    }
    public Vehiculo(String matricula, Cliente cliente, String marca, Set citas) {
       this.matricula = matricula;
       this.cliente = cliente;
       this.marca = marca;
       this.citas = citas;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


